version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chanwi-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chanwi-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8080"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/chanwi-db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code

volumes:
  postgres_data: